import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule, MatProgressBarModule, MatCardModule, MatFormFieldModule, MatIconModule, MatInputModule, MatMenuModule, MatSidenavModule,
  MatToolbarModule, MatTooltipModule, MatProgressSpinnerModule, MatTabsModule, MatButtonToggleModule, MatListModule, MatCheckboxModule, MatStepperModule, MatChipsModule, MatCommonModule, MatDialogModule
  , MatExpansionModule, MatLineModule, MatGridListModule, MatRadioModule, MatSelectModule, MatSliderModule
} from '@angular/material';
@NgModule({
  imports: [  MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSidenavModule,
    MatFormFieldModule,
    MatInputModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatTabsModule,
    MatButtonToggleModule,
    MatProgressBarModule,
    MatListModule,
    MatCheckboxModule,
    MatStepperModule,
    MatChipsModule,
    MatCommonModule,
    MatDialogModule,
    MatExpansionModule,
    MatLineModule,
    MatGridListModule,
    MatRadioModule,
    MatSliderModule,
    MatSelectModule],
  exports: [  MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSidenavModule,
    MatFormFieldModule,
    MatInputModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatTabsModule,
    MatButtonToggleModule,
    MatProgressBarModule,
    MatListModule,
    MatCheckboxModule,
    MatStepperModule,
    MatChipsModule,
    MatCommonModule,
    MatDialogModule,
    MatExpansionModule,
    MatLineModule,
    MatGridListModule,
    MatRadioModule,
    MatSliderModule,
    MatSelectModule],
})
export class MaterialModule { }
